[package]
name = "sha-1"
version = "0.9.4"
description = "SHA-1 hash function"
authors = ["RustCrypto Developers"]
license = "MIT OR Apache-2.0"
readme = "README.md"
edition = "2018"
documentation = "https://docs.rs/sha-1"
repository = "https://github.com/RustCrypto/hashes"
keywords = ["crypto", "sha1", "hash", "digest"]
categories = ["cryptography", "no-std"]

[lib]
name = "sha1"

[dependencies]
digest = { version = "0.10.0-pre.3", features = ["core-api"] }
cfg-if = "1.0"
sha1-asm = { version = "0.5", optional = true }

[target.'cfg(any(target_arch = "x86", target_arch = "x86_64"))'.dependencies]
cpuid-bool = "0.1"

[target.'cfg(all(target_arch = "aarch64", target_os = "linux"))'.dependencies]
libc = { version = "0.2.86", optional = true }

[dev-dependencies]
digest = { version = "0.10.0-pre.3", features = ["dev"] }
hex-literal = "0.2"

[features]
default = ["std"]
std = ["digest/std"]
asm = ["sha1-asm", "libc"]
compress = [] # Expose compress function
force-soft = [] # Force software implementation

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]
