[package]
name = "gost94"
version = "0.9.1"
description = "GOST R 34.11-94 hash function"
authors = ["RustCrypto Developers"]
license = "MIT OR Apache-2.0"
readme = "README.md"
edition = "2018"
documentation = "https://docs.rs/gost94"
repository = "https://github.com/RustCrypto/hashes"
keywords = ["crypto", "gost94", "gost", "hash", "digest"]
categories = ["cryptography", "no-std"]

[dependencies]
digest = { version = "0.10.0-pre.3", features = ["core-api", "block-padding"] }

[dev-dependencies]
digest = { version = "0.10.0-pre.3", features = ["dev"] }
hex-literal = "0.2"

[features]
default = ["std"]
std = ["digest/std"]
